// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_command.proto

#ifndef PROTOBUF_query_5fcommand_2eproto__INCLUDED
#define PROTOBUF_query_5fcommand_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace proto {
namespace db {
class query_command;
class query_commandDefaultTypeInternal;
extern query_commandDefaultTypeInternal _query_command_default_instance_;
}  // namespace db
}  // namespace proto

namespace proto {
namespace db {

namespace protobuf_query_5fcommand_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_query_5fcommand_2eproto

// ===================================================================

class query_command : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto.db.query_command) */ {
 public:
  query_command();
  virtual ~query_command();

  query_command(const query_command& from);

  inline query_command& operator=(const query_command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const query_command& default_instance();

  static inline const query_command* internal_default_instance() {
    return reinterpret_cast<const query_command*>(
               &_query_command_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(query_command* other);

  // implements Message ----------------------------------------------

  inline query_command* New() const PROTOBUF_FINAL { return New(NULL); }

  query_command* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const query_command& from);
  void MergeFrom(const query_command& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(query_command* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes args = 4;
  int args_size() const;
  void clear_args();
  static const int kArgsFieldNumber = 4;
  const ::std::string& args(int index) const;
  ::std::string* mutable_args(int index);
  void set_args(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_args(int index, ::std::string&& value);
  #endif
  void set_args(int index, const char* value);
  void set_args(int index, const void* value, size_t size);
  ::std::string* add_args();
  void add_args(const ::std::string& value);
  #if LANG_CXX11
  void add_args(::std::string&& value);
  #endif
  void add_args(const char* value);
  void add_args(const void* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& args() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_args();

  // required string table_name = 2;
  bool has_table_name() const;
  void clear_table_name();
  static const int kTableNameFieldNumber = 2;
  const ::std::string& table_name() const;
  void set_table_name(const ::std::string& value);
  #if LANG_CXX11
  void set_table_name(::std::string&& value);
  #endif
  void set_table_name(const char* value);
  void set_table_name(const char* value, size_t size);
  ::std::string* mutable_table_name();
  ::std::string* release_table_name();
  void set_allocated_table_name(::std::string* table_name);

  // required string where_clause = 3;
  bool has_where_clause() const;
  void clear_where_clause();
  static const int kWhereClauseFieldNumber = 3;
  const ::std::string& where_clause() const;
  void set_where_clause(const ::std::string& value);
  #if LANG_CXX11
  void set_where_clause(::std::string&& value);
  #endif
  void set_where_clause(const char* value);
  void set_where_clause(const char* value, size_t size);
  ::std::string* mutable_where_clause();
  ::std::string* release_where_clause();
  void set_allocated_where_clause(::std::string* where_clause);

  // required uint32 channel_id = 1;
  bool has_channel_id() const;
  void clear_channel_id();
  static const int kChannelIdFieldNumber = 1;
  ::google::protobuf::uint32 channel_id() const;
  void set_channel_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto.db.query_command)
 private:
  void set_has_channel_id();
  void clear_has_channel_id();
  void set_has_table_name();
  void clear_has_table_name();
  void set_has_where_clause();
  void clear_has_where_clause();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> args_;
  ::google::protobuf::internal::ArenaStringPtr table_name_;
  ::google::protobuf::internal::ArenaStringPtr where_clause_;
  ::google::protobuf::uint32 channel_id_;
  friend struct protobuf_query_5fcommand_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// query_command

// required uint32 channel_id = 1;
inline bool query_command::has_channel_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void query_command::set_has_channel_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void query_command::clear_has_channel_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void query_command::clear_channel_id() {
  channel_id_ = 0u;
  clear_has_channel_id();
}
inline ::google::protobuf::uint32 query_command::channel_id() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.channel_id)
  return channel_id_;
}
inline void query_command::set_channel_id(::google::protobuf::uint32 value) {
  set_has_channel_id();
  channel_id_ = value;
  // @@protoc_insertion_point(field_set:proto.db.query_command.channel_id)
}

// required string table_name = 2;
inline bool query_command::has_table_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void query_command::set_has_table_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void query_command::clear_has_table_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void query_command::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_table_name();
}
inline const ::std::string& query_command::table_name() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.table_name)
  return table_name_.GetNoArena();
}
inline void query_command::set_table_name(const ::std::string& value) {
  set_has_table_name();
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.query_command.table_name)
}
#if LANG_CXX11
inline void query_command::set_table_name(::std::string&& value) {
  set_has_table_name();
  table_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.db.query_command.table_name)
}
#endif
inline void query_command::set_table_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_table_name();
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.table_name)
}
inline void query_command::set_table_name(const char* value, size_t size) {
  set_has_table_name();
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.table_name)
}
inline ::std::string* query_command::mutable_table_name() {
  set_has_table_name();
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.table_name)
  return table_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* query_command::release_table_name() {
  // @@protoc_insertion_point(field_release:proto.db.query_command.table_name)
  clear_has_table_name();
  return table_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_command::set_allocated_table_name(::std::string* table_name) {
  if (table_name != NULL) {
    set_has_table_name();
  } else {
    clear_has_table_name();
  }
  table_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), table_name);
  // @@protoc_insertion_point(field_set_allocated:proto.db.query_command.table_name)
}

// required string where_clause = 3;
inline bool query_command::has_where_clause() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void query_command::set_has_where_clause() {
  _has_bits_[0] |= 0x00000002u;
}
inline void query_command::clear_has_where_clause() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void query_command::clear_where_clause() {
  where_clause_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_where_clause();
}
inline const ::std::string& query_command::where_clause() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.where_clause)
  return where_clause_.GetNoArena();
}
inline void query_command::set_where_clause(const ::std::string& value) {
  set_has_where_clause();
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.query_command.where_clause)
}
#if LANG_CXX11
inline void query_command::set_where_clause(::std::string&& value) {
  set_has_where_clause();
  where_clause_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.db.query_command.where_clause)
}
#endif
inline void query_command::set_where_clause(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_where_clause();
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.where_clause)
}
inline void query_command::set_where_clause(const char* value, size_t size) {
  set_has_where_clause();
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.where_clause)
}
inline ::std::string* query_command::mutable_where_clause() {
  set_has_where_clause();
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.where_clause)
  return where_clause_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* query_command::release_where_clause() {
  // @@protoc_insertion_point(field_release:proto.db.query_command.where_clause)
  clear_has_where_clause();
  return where_clause_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void query_command::set_allocated_where_clause(::std::string* where_clause) {
  if (where_clause != NULL) {
    set_has_where_clause();
  } else {
    clear_has_where_clause();
  }
  where_clause_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), where_clause);
  // @@protoc_insertion_point(field_set_allocated:proto.db.query_command.where_clause)
}

// repeated bytes args = 4;
inline int query_command::args_size() const {
  return args_.size();
}
inline void query_command::clear_args() {
  args_.Clear();
}
inline const ::std::string& query_command::args(int index) const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.args)
  return args_.Get(index);
}
inline ::std::string* query_command::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.args)
  return args_.Mutable(index);
}
inline void query_command::set_args(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:proto.db.query_command.args)
  args_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void query_command::set_args(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:proto.db.query_command.args)
  args_.Mutable(index)->assign(std::move(value));
}
#endif
inline void query_command::set_args(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  args_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.args)
}
inline void query_command::set_args(int index, const void* value, size_t size) {
  args_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.args)
}
inline ::std::string* query_command::add_args() {
  // @@protoc_insertion_point(field_add_mutable:proto.db.query_command.args)
  return args_.Add();
}
inline void query_command::add_args(const ::std::string& value) {
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:proto.db.query_command.args)
}
#if LANG_CXX11
inline void query_command::add_args(::std::string&& value) {
  args_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:proto.db.query_command.args)
}
#endif
inline void query_command::add_args(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:proto.db.query_command.args)
}
inline void query_command::add_args(const void* value, size_t size) {
  args_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:proto.db.query_command.args)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
query_command::args() const {
  // @@protoc_insertion_point(field_list:proto.db.query_command.args)
  return args_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
query_command::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:proto.db.query_command.args)
  return &args_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_query_5fcommand_2eproto__INCLUDED
