// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_command.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "query_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {
class query_commandDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<query_command> {
} _query_command_default_instance_;

namespace protobuf_query_5fcommand_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(query_command, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(query_command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(query_command, channel_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(query_command, table_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(query_command, where_clause_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(query_command, args_),
  2,
  0,
  1,
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 9, sizeof(query_command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_query_command_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "query_command.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _query_command_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _query_command_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\023query_command.proto\022\010proto.db\"[\n\rquery"
      "_command\022\022\n\nchannel_id\030\001 \002(\r\022\022\n\ntable_na"
      "me\030\002 \002(\t\022\024\n\014where_clause\030\003 \002(\t\022\014\n\004args\030\004"
      " \003(\014"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 124);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "query_command.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_query_5fcommand_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int query_command::kChannelIdFieldNumber;
const int query_command::kTableNameFieldNumber;
const int query_command::kWhereClauseFieldNumber;
const int query_command::kArgsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

query_command::query_command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_query_5fcommand_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.db.query_command)
}
query_command::query_command(const query_command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      args_(from.args_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  table_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_table_name()) {
    table_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_name_);
  }
  where_clause_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_where_clause()) {
    where_clause_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.where_clause_);
  }
  channel_id_ = from.channel_id_;
  // @@protoc_insertion_point(copy_constructor:proto.db.query_command)
}

void query_command::SharedCtor() {
  _cached_size_ = 0;
  table_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  where_clause_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  channel_id_ = 0u;
}

query_command::~query_command() {
  // @@protoc_insertion_point(destructor:proto.db.query_command)
  SharedDtor();
}

void query_command::SharedDtor() {
  table_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  where_clause_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void query_command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* query_command::descriptor() {
  protobuf_query_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_query_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const query_command& query_command::default_instance() {
  protobuf_query_5fcommand_2eproto::InitDefaults();
  return *internal_default_instance();
}

query_command* query_command::New(::google::protobuf::Arena* arena) const {
  query_command* n = new query_command;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void query_command::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.db.query_command)
  args_.Clear();
  if (_has_bits_[0 / 32] & 3u) {
    if (has_table_name()) {
      GOOGLE_DCHECK(!table_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*table_name_.UnsafeRawStringPointer())->clear();
    }
    if (has_where_clause()) {
      GOOGLE_DCHECK(!where_clause_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*where_clause_.UnsafeRawStringPointer())->clear();
    }
  }
  channel_id_ = 0u;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool query_command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.db.query_command)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 channel_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_channel_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &channel_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string table_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_table_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->table_name().data(), this->table_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto.db.query_command.table_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string where_clause = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_where_clause()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->where_clause().data(), this->where_clause().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto.db.query_command.where_clause");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated bytes args = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->add_args()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.db.query_command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.db.query_command)
  return false;
#undef DO_
}

void query_command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.db.query_command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 channel_id = 1;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->channel_id(), output);
  }

  // required string table_name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->table_name().data(), this->table_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.db.query_command.table_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->table_name(), output);
  }

  // required string where_clause = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->where_clause().data(), this->where_clause().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.db.query_command.where_clause");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->where_clause(), output);
  }

  // repeated bytes args = 4;
  for (int i = 0, n = this->args_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      4, this->args(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.db.query_command)
}

::google::protobuf::uint8* query_command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.db.query_command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 channel_id = 1;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->channel_id(), target);
  }

  // required string table_name = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->table_name().data(), this->table_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.db.query_command.table_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->table_name(), target);
  }

  // required string where_clause = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->where_clause().data(), this->where_clause().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.db.query_command.where_clause");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->where_clause(), target);
  }

  // repeated bytes args = 4;
  for (int i = 0, n = this->args_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBytesToArray(4, this->args(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.db.query_command)
  return target;
}

size_t query_command::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:proto.db.query_command)
  size_t total_size = 0;

  if (has_table_name()) {
    // required string table_name = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table_name());
  }

  if (has_where_clause()) {
    // required string where_clause = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->where_clause());
  }

  if (has_channel_id()) {
    // required uint32 channel_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->channel_id());
  }

  return total_size;
}
size_t query_command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.db.query_command)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string table_name = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->table_name());

    // required string where_clause = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->where_clause());

    // required uint32 channel_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->channel_id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated bytes args = 4;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->args_size());
  for (int i = 0, n = this->args_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
      this->args(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void query_command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.db.query_command)
  GOOGLE_DCHECK_NE(&from, this);
  const query_command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const query_command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.db.query_command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.db.query_command)
    MergeFrom(*source);
  }
}

void query_command::MergeFrom(const query_command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.db.query_command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  args_.MergeFrom(from.args_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_table_name();
      table_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.table_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_where_clause();
      where_clause_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.where_clause_);
    }
    if (cached_has_bits & 0x00000004u) {
      channel_id_ = from.channel_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void query_command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.db.query_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void query_command::CopyFrom(const query_command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.db.query_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool query_command::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void query_command::Swap(query_command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void query_command::InternalSwap(query_command* other) {
  args_.InternalSwap(&other->args_);
  table_name_.Swap(&other->table_name_);
  where_clause_.Swap(&other->where_clause_);
  std::swap(channel_id_, other->channel_id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata query_command::GetMetadata() const {
  protobuf_query_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_query_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// query_command

// required uint32 channel_id = 1;
bool query_command::has_channel_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void query_command::set_has_channel_id() {
  _has_bits_[0] |= 0x00000004u;
}
void query_command::clear_has_channel_id() {
  _has_bits_[0] &= ~0x00000004u;
}
void query_command::clear_channel_id() {
  channel_id_ = 0u;
  clear_has_channel_id();
}
::google::protobuf::uint32 query_command::channel_id() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.channel_id)
  return channel_id_;
}
void query_command::set_channel_id(::google::protobuf::uint32 value) {
  set_has_channel_id();
  channel_id_ = value;
  // @@protoc_insertion_point(field_set:proto.db.query_command.channel_id)
}

// required string table_name = 2;
bool query_command::has_table_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void query_command::set_has_table_name() {
  _has_bits_[0] |= 0x00000001u;
}
void query_command::clear_has_table_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void query_command::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_table_name();
}
const ::std::string& query_command::table_name() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.table_name)
  return table_name_.GetNoArena();
}
void query_command::set_table_name(const ::std::string& value) {
  set_has_table_name();
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.query_command.table_name)
}
#if LANG_CXX11
void query_command::set_table_name(::std::string&& value) {
  set_has_table_name();
  table_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.db.query_command.table_name)
}
#endif
void query_command::set_table_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_table_name();
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.table_name)
}
void query_command::set_table_name(const char* value, size_t size) {
  set_has_table_name();
  table_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.table_name)
}
::std::string* query_command::mutable_table_name() {
  set_has_table_name();
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.table_name)
  return table_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* query_command::release_table_name() {
  // @@protoc_insertion_point(field_release:proto.db.query_command.table_name)
  clear_has_table_name();
  return table_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void query_command::set_allocated_table_name(::std::string* table_name) {
  if (table_name != NULL) {
    set_has_table_name();
  } else {
    clear_has_table_name();
  }
  table_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), table_name);
  // @@protoc_insertion_point(field_set_allocated:proto.db.query_command.table_name)
}

// required string where_clause = 3;
bool query_command::has_where_clause() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void query_command::set_has_where_clause() {
  _has_bits_[0] |= 0x00000002u;
}
void query_command::clear_has_where_clause() {
  _has_bits_[0] &= ~0x00000002u;
}
void query_command::clear_where_clause() {
  where_clause_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_where_clause();
}
const ::std::string& query_command::where_clause() const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.where_clause)
  return where_clause_.GetNoArena();
}
void query_command::set_where_clause(const ::std::string& value) {
  set_has_where_clause();
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.query_command.where_clause)
}
#if LANG_CXX11
void query_command::set_where_clause(::std::string&& value) {
  set_has_where_clause();
  where_clause_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.db.query_command.where_clause)
}
#endif
void query_command::set_where_clause(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_where_clause();
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.where_clause)
}
void query_command::set_where_clause(const char* value, size_t size) {
  set_has_where_clause();
  where_clause_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.where_clause)
}
::std::string* query_command::mutable_where_clause() {
  set_has_where_clause();
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.where_clause)
  return where_clause_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* query_command::release_where_clause() {
  // @@protoc_insertion_point(field_release:proto.db.query_command.where_clause)
  clear_has_where_clause();
  return where_clause_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void query_command::set_allocated_where_clause(::std::string* where_clause) {
  if (where_clause != NULL) {
    set_has_where_clause();
  } else {
    clear_has_where_clause();
  }
  where_clause_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), where_clause);
  // @@protoc_insertion_point(field_set_allocated:proto.db.query_command.where_clause)
}

// repeated bytes args = 4;
int query_command::args_size() const {
  return args_.size();
}
void query_command::clear_args() {
  args_.Clear();
}
const ::std::string& query_command::args(int index) const {
  // @@protoc_insertion_point(field_get:proto.db.query_command.args)
  return args_.Get(index);
}
::std::string* query_command::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:proto.db.query_command.args)
  return args_.Mutable(index);
}
void query_command::set_args(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:proto.db.query_command.args)
  args_.Mutable(index)->assign(value);
}
#if LANG_CXX11
void query_command::set_args(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:proto.db.query_command.args)
  args_.Mutable(index)->assign(std::move(value));
}
#endif
void query_command::set_args(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  args_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.db.query_command.args)
}
void query_command::set_args(int index, const void* value, size_t size) {
  args_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.db.query_command.args)
}
::std::string* query_command::add_args() {
  // @@protoc_insertion_point(field_add_mutable:proto.db.query_command.args)
  return args_.Add();
}
void query_command::add_args(const ::std::string& value) {
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:proto.db.query_command.args)
}
#if LANG_CXX11
void query_command::add_args(::std::string&& value) {
  args_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:proto.db.query_command.args)
}
#endif
void query_command::add_args(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:proto.db.query_command.args)
}
void query_command::add_args(const void* value, size_t size) {
  args_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:proto.db.query_command.args)
}
const ::google::protobuf::RepeatedPtrField< ::std::string>&
query_command::args() const {
  // @@protoc_insertion_point(field_list:proto.db.query_command.args)
  return args_;
}
::google::protobuf::RepeatedPtrField< ::std::string>*
query_command::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:proto.db.query_command.args)
  return &args_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)
