// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update_command.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "update_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace db {
class update_commandDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<update_command> {
} _update_command_default_instance_;

namespace protobuf_update_5fcommand_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(update_command, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(update_command, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(update_command, message_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(update_command, message_content_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(update_command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_update_command_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "update_command.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _update_command_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _update_command_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\024update_command.proto\022\010proto.db\"\?\n\016upda"
      "te_command\022\024\n\014message_name\030\001 \002(\t\022\027\n\017mess"
      "age_content\030\002 \002(\014"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 97);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "update_command.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_update_5fcommand_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int update_command::kMessageNameFieldNumber;
const int update_command::kMessageContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

update_command::update_command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_update_5fcommand_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.db.update_command)
}
update_command::update_command(const update_command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_message_name()) {
    message_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_name_);
  }
  message_content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_message_content()) {
    message_content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_content_);
  }
  // @@protoc_insertion_point(copy_constructor:proto.db.update_command)
}

void update_command::SharedCtor() {
  _cached_size_ = 0;
  message_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

update_command::~update_command() {
  // @@protoc_insertion_point(destructor:proto.db.update_command)
  SharedDtor();
}

void update_command::SharedDtor() {
  message_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void update_command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* update_command::descriptor() {
  protobuf_update_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_update_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const update_command& update_command::default_instance() {
  protobuf_update_5fcommand_2eproto::InitDefaults();
  return *internal_default_instance();
}

update_command* update_command::New(::google::protobuf::Arena* arena) const {
  update_command* n = new update_command;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void update_command::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.db.update_command)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_message_name()) {
      GOOGLE_DCHECK(!message_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*message_name_.UnsafeRawStringPointer())->clear();
    }
    if (has_message_content()) {
      GOOGLE_DCHECK(!message_content_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*message_content_.UnsafeRawStringPointer())->clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool update_command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.db.update_command)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string message_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message_name().data(), this->message_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto.db.update_command.message_name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes message_content = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_message_content()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.db.update_command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.db.update_command)
  return false;
#undef DO_
}

void update_command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.db.update_command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string message_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message_name().data(), this->message_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.db.update_command.message_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message_name(), output);
  }

  // required bytes message_content = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->message_content(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.db.update_command)
}

::google::protobuf::uint8* update_command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.db.update_command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string message_name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message_name().data(), this->message_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.db.update_command.message_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message_name(), target);
  }

  // required bytes message_content = 2;
  if (cached_has_bits & 0x00000002u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->message_content(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.db.update_command)
  return target;
}

size_t update_command::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:proto.db.update_command)
  size_t total_size = 0;

  if (has_message_name()) {
    // required string message_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message_name());
  }

  if (has_message_content()) {
    // required bytes message_content = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->message_content());
  }

  return total_size;
}
size_t update_command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.db.update_command)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string message_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message_name());

    // required bytes message_content = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->message_content());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void update_command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.db.update_command)
  GOOGLE_DCHECK_NE(&from, this);
  const update_command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const update_command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.db.update_command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.db.update_command)
    MergeFrom(*source);
  }
}

void update_command::MergeFrom(const update_command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.db.update_command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_message_name();
      message_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_message_content();
      message_content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_content_);
    }
  }
}

void update_command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.db.update_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void update_command::CopyFrom(const update_command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.db.update_command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool update_command::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void update_command::Swap(update_command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void update_command::InternalSwap(update_command* other) {
  message_name_.Swap(&other->message_name_);
  message_content_.Swap(&other->message_content_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata update_command::GetMetadata() const {
  protobuf_update_5fcommand_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_update_5fcommand_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// update_command

// required string message_name = 1;
bool update_command::has_message_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void update_command::set_has_message_name() {
  _has_bits_[0] |= 0x00000001u;
}
void update_command::clear_has_message_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void update_command::clear_message_name() {
  message_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message_name();
}
const ::std::string& update_command::message_name() const {
  // @@protoc_insertion_point(field_get:proto.db.update_command.message_name)
  return message_name_.GetNoArena();
}
void update_command::set_message_name(const ::std::string& value) {
  set_has_message_name();
  message_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.update_command.message_name)
}
#if LANG_CXX11
void update_command::set_message_name(::std::string&& value) {
  set_has_message_name();
  message_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.db.update_command.message_name)
}
#endif
void update_command::set_message_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_message_name();
  message_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.update_command.message_name)
}
void update_command::set_message_name(const char* value, size_t size) {
  set_has_message_name();
  message_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.update_command.message_name)
}
::std::string* update_command::mutable_message_name() {
  set_has_message_name();
  // @@protoc_insertion_point(field_mutable:proto.db.update_command.message_name)
  return message_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* update_command::release_message_name() {
  // @@protoc_insertion_point(field_release:proto.db.update_command.message_name)
  clear_has_message_name();
  return message_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void update_command::set_allocated_message_name(::std::string* message_name) {
  if (message_name != NULL) {
    set_has_message_name();
  } else {
    clear_has_message_name();
  }
  message_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message_name);
  // @@protoc_insertion_point(field_set_allocated:proto.db.update_command.message_name)
}

// required bytes message_content = 2;
bool update_command::has_message_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void update_command::set_has_message_content() {
  _has_bits_[0] |= 0x00000002u;
}
void update_command::clear_has_message_content() {
  _has_bits_[0] &= ~0x00000002u;
}
void update_command::clear_message_content() {
  message_content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_message_content();
}
const ::std::string& update_command::message_content() const {
  // @@protoc_insertion_point(field_get:proto.db.update_command.message_content)
  return message_content_.GetNoArena();
}
void update_command::set_message_content(const ::std::string& value) {
  set_has_message_content();
  message_content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:proto.db.update_command.message_content)
}
#if LANG_CXX11
void update_command::set_message_content(::std::string&& value) {
  set_has_message_content();
  message_content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:proto.db.update_command.message_content)
}
#endif
void update_command::set_message_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_message_content();
  message_content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:proto.db.update_command.message_content)
}
void update_command::set_message_content(const void* value, size_t size) {
  set_has_message_content();
  message_content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:proto.db.update_command.message_content)
}
::std::string* update_command::mutable_message_content() {
  set_has_message_content();
  // @@protoc_insertion_point(field_mutable:proto.db.update_command.message_content)
  return message_content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* update_command::release_message_content() {
  // @@protoc_insertion_point(field_release:proto.db.update_command.message_content)
  clear_has_message_content();
  return message_content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void update_command::set_allocated_message_content(::std::string* message_content) {
  if (message_content != NULL) {
    set_has_message_content();
  } else {
    clear_has_message_content();
  }
  message_content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message_content);
  // @@protoc_insertion_point(field_set_allocated:proto.db.update_command.message_content)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace db
}  // namespace proto

// @@protoc_insertion_point(global_scope)
