// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_token_notify.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "player_token_notify.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class player_token_notifyDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<player_token_notify> {
} _player_token_notify_default_instance_;

namespace protobuf_player_5ftoken_5fnotify_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_token_notify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_token_notify, player_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_token_notify, gas_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_token_notify, token_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(player_token_notify)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_player_token_notify_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "player_token_notify.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _player_token_notify_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _player_token_notify_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\031player_token_notify.proto\"G\n\023player_to"
      "ken_notify\022\021\n\tplayer_id\030\001 \001(\004\022\016\n\006gas_id\030"
      "\002 \001(\r\022\r\n\005token\030\003 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 108);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "player_token_notify.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_player_5ftoken_5fnotify_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int player_token_notify::kPlayerIdFieldNumber;
const int player_token_notify::kGasIdFieldNumber;
const int player_token_notify::kTokenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

player_token_notify::player_token_notify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_player_5ftoken_5fnotify_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:player_token_notify)
}
player_token_notify::player_token_notify(const player_token_notify& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.token().size() > 0) {
    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  ::memcpy(&player_id_, &from.player_id_,
    reinterpret_cast<char*>(&gas_id_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(gas_id_));
  // @@protoc_insertion_point(copy_constructor:player_token_notify)
}

void player_token_notify::SharedCtor() {
  token_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&player_id_, 0, reinterpret_cast<char*>(&gas_id_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(gas_id_));
  _cached_size_ = 0;
}

player_token_notify::~player_token_notify() {
  // @@protoc_insertion_point(destructor:player_token_notify)
  SharedDtor();
}

void player_token_notify::SharedDtor() {
  token_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void player_token_notify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* player_token_notify::descriptor() {
  protobuf_player_5ftoken_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_player_5ftoken_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const player_token_notify& player_token_notify::default_instance() {
  protobuf_player_5ftoken_5fnotify_2eproto::InitDefaults();
  return *internal_default_instance();
}

player_token_notify* player_token_notify::New(::google::protobuf::Arena* arena) const {
  player_token_notify* n = new player_token_notify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void player_token_notify::Clear() {
// @@protoc_insertion_point(message_clear_start:player_token_notify)
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&player_id_, 0, reinterpret_cast<char*>(&gas_id_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(gas_id_));
}

bool player_token_notify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:player_token_notify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 player_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &player_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 gas_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &gas_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string token = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_token()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->token().data(), this->token().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "player_token_notify.token"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:player_token_notify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:player_token_notify)
  return false;
#undef DO_
}

void player_token_notify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:player_token_notify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->player_id(), output);
  }

  // uint32 gas_id = 2;
  if (this->gas_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->gas_id(), output);
  }

  // string token = 3;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "player_token_notify.token");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->token(), output);
  }

  // @@protoc_insertion_point(serialize_end:player_token_notify)
}

::google::protobuf::uint8* player_token_notify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:player_token_notify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->player_id(), target);
  }

  // uint32 gas_id = 2;
  if (this->gas_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->gas_id(), target);
  }

  // string token = 3;
  if (this->token().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->token().data(), this->token().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "player_token_notify.token");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->token(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:player_token_notify)
  return target;
}

size_t player_token_notify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:player_token_notify)
  size_t total_size = 0;

  // string token = 3;
  if (this->token().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->token());
  }

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->player_id());
  }

  // uint32 gas_id = 2;
  if (this->gas_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gas_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void player_token_notify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:player_token_notify)
  GOOGLE_DCHECK_NE(&from, this);
  const player_token_notify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const player_token_notify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:player_token_notify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:player_token_notify)
    MergeFrom(*source);
  }
}

void player_token_notify::MergeFrom(const player_token_notify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:player_token_notify)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.token().size() > 0) {

    token_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.token_);
  }
  if (from.player_id() != 0) {
    set_player_id(from.player_id());
  }
  if (from.gas_id() != 0) {
    set_gas_id(from.gas_id());
  }
}

void player_token_notify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:player_token_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void player_token_notify::CopyFrom(const player_token_notify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:player_token_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool player_token_notify::IsInitialized() const {
  return true;
}

void player_token_notify::Swap(player_token_notify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void player_token_notify::InternalSwap(player_token_notify* other) {
  token_.Swap(&other->token_);
  std::swap(player_id_, other->player_id_);
  std::swap(gas_id_, other->gas_id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata player_token_notify::GetMetadata() const {
  protobuf_player_5ftoken_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_player_5ftoken_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// player_token_notify

// uint64 player_id = 1;
void player_token_notify::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 player_token_notify::player_id() const {
  // @@protoc_insertion_point(field_get:player_token_notify.player_id)
  return player_id_;
}
void player_token_notify::set_player_id(::google::protobuf::uint64 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:player_token_notify.player_id)
}

// uint32 gas_id = 2;
void player_token_notify::clear_gas_id() {
  gas_id_ = 0u;
}
::google::protobuf::uint32 player_token_notify::gas_id() const {
  // @@protoc_insertion_point(field_get:player_token_notify.gas_id)
  return gas_id_;
}
void player_token_notify::set_gas_id(::google::protobuf::uint32 value) {
  
  gas_id_ = value;
  // @@protoc_insertion_point(field_set:player_token_notify.gas_id)
}

// string token = 3;
void player_token_notify::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& player_token_notify::token() const {
  // @@protoc_insertion_point(field_get:player_token_notify.token)
  return token_.GetNoArena();
}
void player_token_notify::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:player_token_notify.token)
}
#if LANG_CXX11
void player_token_notify::set_token(::std::string&& value) {
  
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:player_token_notify.token)
}
#endif
void player_token_notify::set_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:player_token_notify.token)
}
void player_token_notify::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:player_token_notify.token)
}
::std::string* player_token_notify::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:player_token_notify.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* player_token_notify::release_token() {
  // @@protoc_insertion_point(field_release:player_token_notify.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void player_token_notify::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:player_token_notify.token)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
