// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_leave_gas_notify.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "player_leave_gas_notify.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class player_leave_gas_notifyDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<player_leave_gas_notify> {
} _player_leave_gas_notify_default_instance_;

namespace protobuf_player_5fleave_5fgas_5fnotify_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_leave_gas_notify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_leave_gas_notify, player_id_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(player_leave_gas_notify)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_player_leave_gas_notify_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "player_leave_gas_notify.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _player_leave_gas_notify_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _player_leave_gas_notify_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\035player_leave_gas_notify.proto\",\n\027playe"
      "r_leave_gas_notify\022\021\n\tplayer_id\030\001 \001(\004b\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "player_leave_gas_notify.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_player_5fleave_5fgas_5fnotify_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int player_leave_gas_notify::kPlayerIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

player_leave_gas_notify::player_leave_gas_notify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_player_5fleave_5fgas_5fnotify_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:player_leave_gas_notify)
}
player_leave_gas_notify::player_leave_gas_notify(const player_leave_gas_notify& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  player_id_ = from.player_id_;
  // @@protoc_insertion_point(copy_constructor:player_leave_gas_notify)
}

void player_leave_gas_notify::SharedCtor() {
  player_id_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

player_leave_gas_notify::~player_leave_gas_notify() {
  // @@protoc_insertion_point(destructor:player_leave_gas_notify)
  SharedDtor();
}

void player_leave_gas_notify::SharedDtor() {
}

void player_leave_gas_notify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* player_leave_gas_notify::descriptor() {
  protobuf_player_5fleave_5fgas_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_player_5fleave_5fgas_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const player_leave_gas_notify& player_leave_gas_notify::default_instance() {
  protobuf_player_5fleave_5fgas_5fnotify_2eproto::InitDefaults();
  return *internal_default_instance();
}

player_leave_gas_notify* player_leave_gas_notify::New(::google::protobuf::Arena* arena) const {
  player_leave_gas_notify* n = new player_leave_gas_notify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void player_leave_gas_notify::Clear() {
// @@protoc_insertion_point(message_clear_start:player_leave_gas_notify)
  player_id_ = GOOGLE_ULONGLONG(0);
}

bool player_leave_gas_notify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:player_leave_gas_notify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 player_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &player_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:player_leave_gas_notify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:player_leave_gas_notify)
  return false;
#undef DO_
}

void player_leave_gas_notify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:player_leave_gas_notify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->player_id(), output);
  }

  // @@protoc_insertion_point(serialize_end:player_leave_gas_notify)
}

::google::protobuf::uint8* player_leave_gas_notify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:player_leave_gas_notify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->player_id(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:player_leave_gas_notify)
  return target;
}

size_t player_leave_gas_notify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:player_leave_gas_notify)
  size_t total_size = 0;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->player_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void player_leave_gas_notify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:player_leave_gas_notify)
  GOOGLE_DCHECK_NE(&from, this);
  const player_leave_gas_notify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const player_leave_gas_notify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:player_leave_gas_notify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:player_leave_gas_notify)
    MergeFrom(*source);
  }
}

void player_leave_gas_notify::MergeFrom(const player_leave_gas_notify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:player_leave_gas_notify)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.player_id() != 0) {
    set_player_id(from.player_id());
  }
}

void player_leave_gas_notify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:player_leave_gas_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void player_leave_gas_notify::CopyFrom(const player_leave_gas_notify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:player_leave_gas_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool player_leave_gas_notify::IsInitialized() const {
  return true;
}

void player_leave_gas_notify::Swap(player_leave_gas_notify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void player_leave_gas_notify::InternalSwap(player_leave_gas_notify* other) {
  std::swap(player_id_, other->player_id_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata player_leave_gas_notify::GetMetadata() const {
  protobuf_player_5fleave_5fgas_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_player_5fleave_5fgas_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// player_leave_gas_notify

// uint64 player_id = 1;
void player_leave_gas_notify::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 player_leave_gas_notify::player_id() const {
  // @@protoc_insertion_point(field_get:player_leave_gas_notify.player_id)
  return player_id_;
}
void player_leave_gas_notify::set_player_id(::google::protobuf::uint64 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:player_leave_gas_notify.player_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
