// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player_enter_gas_response.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "player_enter_gas_response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class player_enter_gas_responseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<player_enter_gas_response> {
} _player_enter_gas_response_default_instance_;

namespace protobuf_player_5fenter_5fgas_5fresponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_enter_gas_response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_enter_gas_response, player_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(player_enter_gas_response, result_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(player_enter_gas_response)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_player_enter_gas_response_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "player_enter_gas_response.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _player_enter_gas_response_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _player_enter_gas_response_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\037player_enter_gas_response.proto\">\n\031pla"
      "yer_enter_gas_response\022\021\n\tplayer_id\030\001 \001("
      "\004\022\016\n\006result\030\002 \001(\rb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 105);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "player_enter_gas_response.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_player_5fenter_5fgas_5fresponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int player_enter_gas_response::kPlayerIdFieldNumber;
const int player_enter_gas_response::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

player_enter_gas_response::player_enter_gas_response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_player_5fenter_5fgas_5fresponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:player_enter_gas_response)
}
player_enter_gas_response::player_enter_gas_response(const player_enter_gas_response& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&player_id_, &from.player_id_,
    reinterpret_cast<char*>(&result_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(result_));
  // @@protoc_insertion_point(copy_constructor:player_enter_gas_response)
}

void player_enter_gas_response::SharedCtor() {
  ::memset(&player_id_, 0, reinterpret_cast<char*>(&result_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(result_));
  _cached_size_ = 0;
}

player_enter_gas_response::~player_enter_gas_response() {
  // @@protoc_insertion_point(destructor:player_enter_gas_response)
  SharedDtor();
}

void player_enter_gas_response::SharedDtor() {
}

void player_enter_gas_response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* player_enter_gas_response::descriptor() {
  protobuf_player_5fenter_5fgas_5fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_player_5fenter_5fgas_5fresponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const player_enter_gas_response& player_enter_gas_response::default_instance() {
  protobuf_player_5fenter_5fgas_5fresponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

player_enter_gas_response* player_enter_gas_response::New(::google::protobuf::Arena* arena) const {
  player_enter_gas_response* n = new player_enter_gas_response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void player_enter_gas_response::Clear() {
// @@protoc_insertion_point(message_clear_start:player_enter_gas_response)
  ::memset(&player_id_, 0, reinterpret_cast<char*>(&result_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(result_));
}

bool player_enter_gas_response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:player_enter_gas_response)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 player_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &player_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 result = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:player_enter_gas_response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:player_enter_gas_response)
  return false;
#undef DO_
}

void player_enter_gas_response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:player_enter_gas_response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->player_id(), output);
  }

  // uint32 result = 2;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->result(), output);
  }

  // @@protoc_insertion_point(serialize_end:player_enter_gas_response)
}

::google::protobuf::uint8* player_enter_gas_response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:player_enter_gas_response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->player_id(), target);
  }

  // uint32 result = 2;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->result(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:player_enter_gas_response)
  return target;
}

size_t player_enter_gas_response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:player_enter_gas_response)
  size_t total_size = 0;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->player_id());
  }

  // uint32 result = 2;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void player_enter_gas_response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:player_enter_gas_response)
  GOOGLE_DCHECK_NE(&from, this);
  const player_enter_gas_response* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const player_enter_gas_response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:player_enter_gas_response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:player_enter_gas_response)
    MergeFrom(*source);
  }
}

void player_enter_gas_response::MergeFrom(const player_enter_gas_response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:player_enter_gas_response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.player_id() != 0) {
    set_player_id(from.player_id());
  }
  if (from.result() != 0) {
    set_result(from.result());
  }
}

void player_enter_gas_response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:player_enter_gas_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void player_enter_gas_response::CopyFrom(const player_enter_gas_response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:player_enter_gas_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool player_enter_gas_response::IsInitialized() const {
  return true;
}

void player_enter_gas_response::Swap(player_enter_gas_response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void player_enter_gas_response::InternalSwap(player_enter_gas_response* other) {
  std::swap(player_id_, other->player_id_);
  std::swap(result_, other->result_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata player_enter_gas_response::GetMetadata() const {
  protobuf_player_5fenter_5fgas_5fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_player_5fenter_5fgas_5fresponse_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// player_enter_gas_response

// uint64 player_id = 1;
void player_enter_gas_response::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 player_enter_gas_response::player_id() const {
  // @@protoc_insertion_point(field_get:player_enter_gas_response.player_id)
  return player_id_;
}
void player_enter_gas_response::set_player_id(::google::protobuf::uint64 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:player_enter_gas_response.player_id)
}

// uint32 result = 2;
void player_enter_gas_response::clear_result() {
  result_ = 0u;
}
::google::protobuf::uint32 player_enter_gas_response::result() const {
  // @@protoc_insertion_point(field_get:player_enter_gas_response.result)
  return result_;
}
void player_enter_gas_response::set_result(::google::protobuf::uint32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:player_enter_gas_response.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
