// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d2u_query_gas_id_response.proto

#ifndef PROTOBUF_d2u_5fquery_5fgas_5fid_5fresponse_2eproto__INCLUDED
#define PROTOBUF_d2u_5fquery_5fgas_5fid_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class d2u_query_gas_id_response;
class d2u_query_gas_id_responseDefaultTypeInternal;
extern d2u_query_gas_id_responseDefaultTypeInternal _d2u_query_gas_id_response_default_instance_;

namespace protobuf_d2u_5fquery_5fgas_5fid_5fresponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_d2u_5fquery_5fgas_5fid_5fresponse_2eproto

// ===================================================================

class d2u_query_gas_id_response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:d2u_query_gas_id_response) */ {
 public:
  d2u_query_gas_id_response();
  virtual ~d2u_query_gas_id_response();

  d2u_query_gas_id_response(const d2u_query_gas_id_response& from);

  inline d2u_query_gas_id_response& operator=(const d2u_query_gas_id_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const d2u_query_gas_id_response& default_instance();

  static inline const d2u_query_gas_id_response* internal_default_instance() {
    return reinterpret_cast<const d2u_query_gas_id_response*>(
               &_d2u_query_gas_id_response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(d2u_query_gas_id_response* other);

  // implements Message ----------------------------------------------

  inline d2u_query_gas_id_response* New() const PROTOBUF_FINAL { return New(NULL); }

  d2u_query_gas_id_response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const d2u_query_gas_id_response& from);
  void MergeFrom(const d2u_query_gas_id_response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(d2u_query_gas_id_response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 player_id = 1;
  bool has_player_id() const;
  void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  ::google::protobuf::uint64 player_id() const;
  void set_player_id(::google::protobuf::uint64 value);

  // required uint32 gas_id = 2;
  bool has_gas_id() const;
  void clear_gas_id();
  static const int kGasIdFieldNumber = 2;
  ::google::protobuf::uint32 gas_id() const;
  void set_gas_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:d2u_query_gas_id_response)
 private:
  void set_has_player_id();
  void clear_has_player_id();
  void set_has_gas_id();
  void clear_has_gas_id();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 player_id_;
  ::google::protobuf::uint32 gas_id_;
  friend struct protobuf_d2u_5fquery_5fgas_5fid_5fresponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// d2u_query_gas_id_response

// required uint64 player_id = 1;
inline bool d2u_query_gas_id_response::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void d2u_query_gas_id_response::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void d2u_query_gas_id_response::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void d2u_query_gas_id_response::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
  clear_has_player_id();
}
inline ::google::protobuf::uint64 d2u_query_gas_id_response::player_id() const {
  // @@protoc_insertion_point(field_get:d2u_query_gas_id_response.player_id)
  return player_id_;
}
inline void d2u_query_gas_id_response::set_player_id(::google::protobuf::uint64 value) {
  set_has_player_id();
  player_id_ = value;
  // @@protoc_insertion_point(field_set:d2u_query_gas_id_response.player_id)
}

// required uint32 gas_id = 2;
inline bool d2u_query_gas_id_response::has_gas_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void d2u_query_gas_id_response::set_has_gas_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void d2u_query_gas_id_response::clear_has_gas_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void d2u_query_gas_id_response::clear_gas_id() {
  gas_id_ = 0u;
  clear_has_gas_id();
}
inline ::google::protobuf::uint32 d2u_query_gas_id_response::gas_id() const {
  // @@protoc_insertion_point(field_get:d2u_query_gas_id_response.gas_id)
  return gas_id_;
}
inline void d2u_query_gas_id_response::set_gas_id(::google::protobuf::uint32 value) {
  set_has_gas_id();
  gas_id_ = value;
  // @@protoc_insertion_point(field_set:d2u_query_gas_id_response.gas_id)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_d2u_5fquery_5fgas_5fid_5fresponse_2eproto__INCLUDED
