// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2c_player_attribute_notify.proto

#ifndef PROTOBUF_s2c_5fplayer_5fattribute_5fnotify_2eproto__INCLUDED
#define PROTOBUF_s2c_5fplayer_5fattribute_5fnotify_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class s2c_player_attribute_notify;
class s2c_player_attribute_notifyDefaultTypeInternal;
extern s2c_player_attribute_notifyDefaultTypeInternal _s2c_player_attribute_notify_default_instance_;

namespace protobuf_s2c_5fplayer_5fattribute_5fnotify_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_s2c_5fplayer_5fattribute_5fnotify_2eproto

// ===================================================================

class s2c_player_attribute_notify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s2c_player_attribute_notify) */ {
 public:
  s2c_player_attribute_notify();
  virtual ~s2c_player_attribute_notify();

  s2c_player_attribute_notify(const s2c_player_attribute_notify& from);

  inline s2c_player_attribute_notify& operator=(const s2c_player_attribute_notify& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const s2c_player_attribute_notify& default_instance();

  static inline const s2c_player_attribute_notify* internal_default_instance() {
    return reinterpret_cast<const s2c_player_attribute_notify*>(
               &_s2c_player_attribute_notify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(s2c_player_attribute_notify* other);

  // implements Message ----------------------------------------------

  inline s2c_player_attribute_notify* New() const PROTOBUF_FINAL { return New(NULL); }

  s2c_player_attribute_notify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const s2c_player_attribute_notify& from);
  void MergeFrom(const s2c_player_attribute_notify& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(s2c_player_attribute_notify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 2;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required uint64 gold = 4;
  bool has_gold() const;
  void clear_gold();
  static const int kGoldFieldNumber = 4;
  ::google::protobuf::uint64 gold() const;
  void set_gold(::google::protobuf::uint64 value);

  // required uint64 money = 5;
  bool has_money() const;
  void clear_money();
  static const int kMoneyFieldNumber = 5;
  ::google::protobuf::uint64 money() const;
  void set_money(::google::protobuf::uint64 value);

  // required uint64 vitality = 6;
  bool has_vitality() const;
  void clear_vitality();
  static const int kVitalityFieldNumber = 6;
  ::google::protobuf::uint64 vitality() const;
  void set_vitality(::google::protobuf::uint64 value);

  // required uint32 lv = 3;
  bool has_lv() const;
  void clear_lv();
  static const int kLvFieldNumber = 3;
  ::google::protobuf::uint32 lv() const;
  void set_lv(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:s2c_player_attribute_notify)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_lv();
  void clear_has_lv();
  void set_has_gold();
  void clear_has_gold();
  void set_has_money();
  void clear_has_money();
  void set_has_vitality();
  void clear_has_vitality();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint64 gold_;
  ::google::protobuf::uint64 money_;
  ::google::protobuf::uint64 vitality_;
  ::google::protobuf::uint32 lv_;
  friend struct protobuf_s2c_5fplayer_5fattribute_5fnotify_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// s2c_player_attribute_notify

// required string name = 2;
inline bool s2c_player_attribute_notify::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void s2c_player_attribute_notify::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void s2c_player_attribute_notify::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void s2c_player_attribute_notify::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& s2c_player_attribute_notify::name() const {
  // @@protoc_insertion_point(field_get:s2c_player_attribute_notify.name)
  return name_.GetNoArena();
}
inline void s2c_player_attribute_notify::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:s2c_player_attribute_notify.name)
}
#if LANG_CXX11
inline void s2c_player_attribute_notify::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:s2c_player_attribute_notify.name)
}
#endif
inline void s2c_player_attribute_notify::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:s2c_player_attribute_notify.name)
}
inline void s2c_player_attribute_notify::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:s2c_player_attribute_notify.name)
}
inline ::std::string* s2c_player_attribute_notify::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:s2c_player_attribute_notify.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* s2c_player_attribute_notify::release_name() {
  // @@protoc_insertion_point(field_release:s2c_player_attribute_notify.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void s2c_player_attribute_notify::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:s2c_player_attribute_notify.name)
}

// required uint32 lv = 3;
inline bool s2c_player_attribute_notify::has_lv() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void s2c_player_attribute_notify::set_has_lv() {
  _has_bits_[0] |= 0x00000010u;
}
inline void s2c_player_attribute_notify::clear_has_lv() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void s2c_player_attribute_notify::clear_lv() {
  lv_ = 0u;
  clear_has_lv();
}
inline ::google::protobuf::uint32 s2c_player_attribute_notify::lv() const {
  // @@protoc_insertion_point(field_get:s2c_player_attribute_notify.lv)
  return lv_;
}
inline void s2c_player_attribute_notify::set_lv(::google::protobuf::uint32 value) {
  set_has_lv();
  lv_ = value;
  // @@protoc_insertion_point(field_set:s2c_player_attribute_notify.lv)
}

// required uint64 gold = 4;
inline bool s2c_player_attribute_notify::has_gold() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void s2c_player_attribute_notify::set_has_gold() {
  _has_bits_[0] |= 0x00000002u;
}
inline void s2c_player_attribute_notify::clear_has_gold() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void s2c_player_attribute_notify::clear_gold() {
  gold_ = GOOGLE_ULONGLONG(0);
  clear_has_gold();
}
inline ::google::protobuf::uint64 s2c_player_attribute_notify::gold() const {
  // @@protoc_insertion_point(field_get:s2c_player_attribute_notify.gold)
  return gold_;
}
inline void s2c_player_attribute_notify::set_gold(::google::protobuf::uint64 value) {
  set_has_gold();
  gold_ = value;
  // @@protoc_insertion_point(field_set:s2c_player_attribute_notify.gold)
}

// required uint64 money = 5;
inline bool s2c_player_attribute_notify::has_money() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void s2c_player_attribute_notify::set_has_money() {
  _has_bits_[0] |= 0x00000004u;
}
inline void s2c_player_attribute_notify::clear_has_money() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void s2c_player_attribute_notify::clear_money() {
  money_ = GOOGLE_ULONGLONG(0);
  clear_has_money();
}
inline ::google::protobuf::uint64 s2c_player_attribute_notify::money() const {
  // @@protoc_insertion_point(field_get:s2c_player_attribute_notify.money)
  return money_;
}
inline void s2c_player_attribute_notify::set_money(::google::protobuf::uint64 value) {
  set_has_money();
  money_ = value;
  // @@protoc_insertion_point(field_set:s2c_player_attribute_notify.money)
}

// required uint64 vitality = 6;
inline bool s2c_player_attribute_notify::has_vitality() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void s2c_player_attribute_notify::set_has_vitality() {
  _has_bits_[0] |= 0x00000008u;
}
inline void s2c_player_attribute_notify::clear_has_vitality() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void s2c_player_attribute_notify::clear_vitality() {
  vitality_ = GOOGLE_ULONGLONG(0);
  clear_has_vitality();
}
inline ::google::protobuf::uint64 s2c_player_attribute_notify::vitality() const {
  // @@protoc_insertion_point(field_get:s2c_player_attribute_notify.vitality)
  return vitality_;
}
inline void s2c_player_attribute_notify::set_vitality(::google::protobuf::uint64 value) {
  set_has_vitality();
  vitality_ = value;
  // @@protoc_insertion_point(field_set:s2c_player_attribute_notify.vitality)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_s2c_5fplayer_5fattribute_5fnotify_2eproto__INCLUDED
