// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2c_player_item_notify.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "s2c_player_item_notify.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class s2c_player_item_dataDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<s2c_player_item_data> {
} _s2c_player_item_data_default_instance_;
class s2c_player_item_notifyDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<s2c_player_item_notify> {
} _s2c_player_item_notify_default_instance_;

namespace protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_data, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_data, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_data, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_data, count_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_notify, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_notify, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s2c_player_item_notify, data_),
  ~0u,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(s2c_player_item_data)},
  { 9, 15, sizeof(s2c_player_item_notify)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_s2c_player_item_data_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_s2c_player_item_notify_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "s2c_player_item_notify.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _s2c_player_item_data_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _s2c_player_item_notify_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _s2c_player_item_data_default_instance_.DefaultConstruct();
  _s2c_player_item_notify_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\034s2c_player_item_notify.proto\"1\n\024s2c_pl"
      "ayer_item_data\022\n\n\002id\030\001 \002(\r\022\r\n\005count\030\002 \002("
      "\r\"=\n\026s2c_player_item_notify\022#\n\004data\030\001 \003("
      "\0132\025.s2c_player_item_data"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 144);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "s2c_player_item_notify.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int s2c_player_item_data::kIdFieldNumber;
const int s2c_player_item_data::kCountFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

s2c_player_item_data::s2c_player_item_data()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:s2c_player_item_data)
}
s2c_player_item_data::s2c_player_item_data(const s2c_player_item_data& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    reinterpret_cast<char*>(&count_) -
    reinterpret_cast<char*>(&id_) + sizeof(count_));
  // @@protoc_insertion_point(copy_constructor:s2c_player_item_data)
}

void s2c_player_item_data::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&id_, 0, reinterpret_cast<char*>(&count_) -
    reinterpret_cast<char*>(&id_) + sizeof(count_));
}

s2c_player_item_data::~s2c_player_item_data() {
  // @@protoc_insertion_point(destructor:s2c_player_item_data)
  SharedDtor();
}

void s2c_player_item_data::SharedDtor() {
}

void s2c_player_item_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* s2c_player_item_data::descriptor() {
  protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const s2c_player_item_data& s2c_player_item_data::default_instance() {
  protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::InitDefaults();
  return *internal_default_instance();
}

s2c_player_item_data* s2c_player_item_data::New(::google::protobuf::Arena* arena) const {
  s2c_player_item_data* n = new s2c_player_item_data;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void s2c_player_item_data::Clear() {
// @@protoc_insertion_point(message_clear_start:s2c_player_item_data)
  if (_has_bits_[0 / 32] & 3u) {
    ::memset(&id_, 0, reinterpret_cast<char*>(&count_) -
      reinterpret_cast<char*>(&id_) + sizeof(count_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool s2c_player_item_data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:s2c_player_item_data)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required uint32 count = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_count();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:s2c_player_item_data)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:s2c_player_item_data)
  return false;
#undef DO_
}

void s2c_player_item_data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:s2c_player_item_data)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required uint32 count = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->count(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:s2c_player_item_data)
}

::google::protobuf::uint8* s2c_player_item_data::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:s2c_player_item_data)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required uint32 count = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->count(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:s2c_player_item_data)
  return target;
}

size_t s2c_player_item_data::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:s2c_player_item_data)
  size_t total_size = 0;

  if (has_id()) {
    // required uint32 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  if (has_count()) {
    // required uint32 count = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->count());
  }

  return total_size;
}
size_t s2c_player_item_data::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:s2c_player_item_data)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint32 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());

    // required uint32 count = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->count());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void s2c_player_item_data::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:s2c_player_item_data)
  GOOGLE_DCHECK_NE(&from, this);
  const s2c_player_item_data* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const s2c_player_item_data>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:s2c_player_item_data)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:s2c_player_item_data)
    MergeFrom(*source);
  }
}

void s2c_player_item_data::MergeFrom(const s2c_player_item_data& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:s2c_player_item_data)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000002u) {
      count_ = from.count_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void s2c_player_item_data::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:s2c_player_item_data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void s2c_player_item_data::CopyFrom(const s2c_player_item_data& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:s2c_player_item_data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool s2c_player_item_data::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void s2c_player_item_data::Swap(s2c_player_item_data* other) {
  if (other == this) return;
  InternalSwap(other);
}
void s2c_player_item_data::InternalSwap(s2c_player_item_data* other) {
  std::swap(id_, other->id_);
  std::swap(count_, other->count_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata s2c_player_item_data::GetMetadata() const {
  protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// s2c_player_item_data

// required uint32 id = 1;
bool s2c_player_item_data::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void s2c_player_item_data::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void s2c_player_item_data::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void s2c_player_item_data::clear_id() {
  id_ = 0u;
  clear_has_id();
}
::google::protobuf::uint32 s2c_player_item_data::id() const {
  // @@protoc_insertion_point(field_get:s2c_player_item_data.id)
  return id_;
}
void s2c_player_item_data::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:s2c_player_item_data.id)
}

// required uint32 count = 2;
bool s2c_player_item_data::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void s2c_player_item_data::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
void s2c_player_item_data::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
void s2c_player_item_data::clear_count() {
  count_ = 0u;
  clear_has_count();
}
::google::protobuf::uint32 s2c_player_item_data::count() const {
  // @@protoc_insertion_point(field_get:s2c_player_item_data.count)
  return count_;
}
void s2c_player_item_data::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:s2c_player_item_data.count)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int s2c_player_item_notify::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

s2c_player_item_notify::s2c_player_item_notify()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:s2c_player_item_notify)
}
s2c_player_item_notify::s2c_player_item_notify(const s2c_player_item_notify& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:s2c_player_item_notify)
}

void s2c_player_item_notify::SharedCtor() {
  _cached_size_ = 0;
}

s2c_player_item_notify::~s2c_player_item_notify() {
  // @@protoc_insertion_point(destructor:s2c_player_item_notify)
  SharedDtor();
}

void s2c_player_item_notify::SharedDtor() {
}

void s2c_player_item_notify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* s2c_player_item_notify::descriptor() {
  protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const s2c_player_item_notify& s2c_player_item_notify::default_instance() {
  protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::InitDefaults();
  return *internal_default_instance();
}

s2c_player_item_notify* s2c_player_item_notify::New(::google::protobuf::Arena* arena) const {
  s2c_player_item_notify* n = new s2c_player_item_notify;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void s2c_player_item_notify::Clear() {
// @@protoc_insertion_point(message_clear_start:s2c_player_item_notify)
  data_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool s2c_player_item_notify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:s2c_player_item_notify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .s2c_player_item_data data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:s2c_player_item_notify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:s2c_player_item_notify)
  return false;
#undef DO_
}

void s2c_player_item_notify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:s2c_player_item_notify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .s2c_player_item_data data = 1;
  for (unsigned int i = 0, n = this->data_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->data(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:s2c_player_item_notify)
}

::google::protobuf::uint8* s2c_player_item_notify::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:s2c_player_item_notify)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .s2c_player_item_data data = 1;
  for (unsigned int i = 0, n = this->data_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->data(i), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:s2c_player_item_notify)
  return target;
}

size_t s2c_player_item_notify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:s2c_player_item_notify)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // repeated .s2c_player_item_data data = 1;
  {
    unsigned int count = this->data_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->data(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void s2c_player_item_notify::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:s2c_player_item_notify)
  GOOGLE_DCHECK_NE(&from, this);
  const s2c_player_item_notify* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const s2c_player_item_notify>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:s2c_player_item_notify)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:s2c_player_item_notify)
    MergeFrom(*source);
  }
}

void s2c_player_item_notify::MergeFrom(const s2c_player_item_notify& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:s2c_player_item_notify)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
}

void s2c_player_item_notify::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:s2c_player_item_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void s2c_player_item_notify::CopyFrom(const s2c_player_item_notify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:s2c_player_item_notify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool s2c_player_item_notify::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->data())) return false;
  return true;
}

void s2c_player_item_notify::Swap(s2c_player_item_notify* other) {
  if (other == this) return;
  InternalSwap(other);
}
void s2c_player_item_notify::InternalSwap(s2c_player_item_notify* other) {
  data_.InternalSwap(&other->data_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata s2c_player_item_notify::GetMetadata() const {
  protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_s2c_5fplayer_5fitem_5fnotify_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// s2c_player_item_notify

// repeated .s2c_player_item_data data = 1;
int s2c_player_item_notify::data_size() const {
  return data_.size();
}
void s2c_player_item_notify::clear_data() {
  data_.Clear();
}
const ::s2c_player_item_data& s2c_player_item_notify::data(int index) const {
  // @@protoc_insertion_point(field_get:s2c_player_item_notify.data)
  return data_.Get(index);
}
::s2c_player_item_data* s2c_player_item_notify::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:s2c_player_item_notify.data)
  return data_.Mutable(index);
}
::s2c_player_item_data* s2c_player_item_notify::add_data() {
  // @@protoc_insertion_point(field_add:s2c_player_item_notify.data)
  return data_.Add();
}
::google::protobuf::RepeatedPtrField< ::s2c_player_item_data >*
s2c_player_item_notify::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:s2c_player_item_notify.data)
  return &data_;
}
const ::google::protobuf::RepeatedPtrField< ::s2c_player_item_data >&
s2c_player_item_notify::data() const {
  // @@protoc_insertion_point(field_list:s2c_player_item_notify.data)
  return data_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
