// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player_login_request.proto

/*
Package player_login_request is a generated protocol buffer package.

It is generated from these files:
	player_login_request.proto

It has these top-level messages:
	PlayerLoginRequest
*/
package player_login_request

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerLoginRequest struct {
	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	ServerId  uint32 `protobuf:"varint,2,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
}

func (m *PlayerLoginRequest) Reset()                    { *m = PlayerLoginRequest{} }
func (m *PlayerLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*PlayerLoginRequest) ProtoMessage()               {}
func (*PlayerLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PlayerLoginRequest) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *PlayerLoginRequest) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerLoginRequest)(nil), "player_login_request")
}

func init() { proto.RegisterFile("player_login_request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xc8, 0x49, 0xac,
	0x4c, 0x2d, 0x8a, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0x8b, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe2, 0x12, 0xc1, 0x26, 0x2b, 0x24, 0xcb, 0xc5,
	0x95, 0x98, 0x9c, 0x9c, 0x5f, 0x9a, 0x57, 0x12, 0x9f, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x12, 0xc4, 0x09, 0x15, 0xf1, 0x4c, 0x11, 0x92, 0xe6, 0xe2, 0x2c, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d,
	0x02, 0xc9, 0x32, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0x71, 0x40, 0x04, 0x3c, 0x53, 0x92, 0xd8, 0xc0,
	0x46, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xc1, 0x53, 0xcf, 0x78, 0x00, 0x00, 0x00,
}
