// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d2u_player_login_response.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "d2u_player_login_response.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class d2u_player_login_responseDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<d2u_player_login_response> {
} _d2u_player_login_response_default_instance_;

namespace protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(d2u_player_login_response, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(d2u_player_login_response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(d2u_player_login_response, player_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(d2u_player_login_response, gas_id_),
  0,
  1,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 7, sizeof(d2u_player_login_response)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_d2u_player_login_response_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "d2u_player_login_response.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _d2u_player_login_response_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _d2u_player_login_response_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\037d2u_player_login_response.proto\">\n\031d2u"
      "_player_login_response\022\021\n\tplayer_id\030\001 \002("
      "\004\022\016\n\006gas_id\030\002 \002(\r"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 97);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "d2u_player_login_response.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int d2u_player_login_response::kPlayerIdFieldNumber;
const int d2u_player_login_response::kGasIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

d2u_player_login_response::d2u_player_login_response()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:d2u_player_login_response)
}
d2u_player_login_response::d2u_player_login_response(const d2u_player_login_response& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&player_id_, &from.player_id_,
    reinterpret_cast<char*>(&gas_id_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(gas_id_));
  // @@protoc_insertion_point(copy_constructor:d2u_player_login_response)
}

void d2u_player_login_response::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&player_id_, 0, reinterpret_cast<char*>(&gas_id_) -
    reinterpret_cast<char*>(&player_id_) + sizeof(gas_id_));
}

d2u_player_login_response::~d2u_player_login_response() {
  // @@protoc_insertion_point(destructor:d2u_player_login_response)
  SharedDtor();
}

void d2u_player_login_response::SharedDtor() {
}

void d2u_player_login_response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* d2u_player_login_response::descriptor() {
  protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const d2u_player_login_response& d2u_player_login_response::default_instance() {
  protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto::InitDefaults();
  return *internal_default_instance();
}

d2u_player_login_response* d2u_player_login_response::New(::google::protobuf::Arena* arena) const {
  d2u_player_login_response* n = new d2u_player_login_response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void d2u_player_login_response::Clear() {
// @@protoc_insertion_point(message_clear_start:d2u_player_login_response)
  if (_has_bits_[0 / 32] & 3u) {
    ::memset(&player_id_, 0, reinterpret_cast<char*>(&gas_id_) -
      reinterpret_cast<char*>(&player_id_) + sizeof(gas_id_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool d2u_player_login_response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:d2u_player_login_response)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 player_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          set_has_player_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &player_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required uint32 gas_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u)) {
          set_has_gas_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &gas_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:d2u_player_login_response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:d2u_player_login_response)
  return false;
#undef DO_
}

void d2u_player_login_response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:d2u_player_login_response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 player_id = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->player_id(), output);
  }

  // required uint32 gas_id = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->gas_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:d2u_player_login_response)
}

::google::protobuf::uint8* d2u_player_login_response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:d2u_player_login_response)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint64 player_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->player_id(), target);
  }

  // required uint32 gas_id = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->gas_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:d2u_player_login_response)
  return target;
}

size_t d2u_player_login_response::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:d2u_player_login_response)
  size_t total_size = 0;

  if (has_player_id()) {
    // required uint64 player_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->player_id());
  }

  if (has_gas_id()) {
    // required uint32 gas_id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gas_id());
  }

  return total_size;
}
size_t d2u_player_login_response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:d2u_player_login_response)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required uint64 player_id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->player_id());

    // required uint32 gas_id = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->gas_id());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void d2u_player_login_response::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:d2u_player_login_response)
  GOOGLE_DCHECK_NE(&from, this);
  const d2u_player_login_response* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const d2u_player_login_response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:d2u_player_login_response)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:d2u_player_login_response)
    MergeFrom(*source);
  }
}

void d2u_player_login_response::MergeFrom(const d2u_player_login_response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:d2u_player_login_response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      player_id_ = from.player_id_;
    }
    if (cached_has_bits & 0x00000002u) {
      gas_id_ = from.gas_id_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void d2u_player_login_response::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:d2u_player_login_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void d2u_player_login_response::CopyFrom(const d2u_player_login_response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:d2u_player_login_response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool d2u_player_login_response::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void d2u_player_login_response::Swap(d2u_player_login_response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void d2u_player_login_response::InternalSwap(d2u_player_login_response* other) {
  std::swap(player_id_, other->player_id_);
  std::swap(gas_id_, other->gas_id_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata d2u_player_login_response::GetMetadata() const {
  protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_d2u_5fplayer_5flogin_5fresponse_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// d2u_player_login_response

// required uint64 player_id = 1;
bool d2u_player_login_response::has_player_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void d2u_player_login_response::set_has_player_id() {
  _has_bits_[0] |= 0x00000001u;
}
void d2u_player_login_response::clear_has_player_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void d2u_player_login_response::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
  clear_has_player_id();
}
::google::protobuf::uint64 d2u_player_login_response::player_id() const {
  // @@protoc_insertion_point(field_get:d2u_player_login_response.player_id)
  return player_id_;
}
void d2u_player_login_response::set_player_id(::google::protobuf::uint64 value) {
  set_has_player_id();
  player_id_ = value;
  // @@protoc_insertion_point(field_set:d2u_player_login_response.player_id)
}

// required uint32 gas_id = 2;
bool d2u_player_login_response::has_gas_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void d2u_player_login_response::set_has_gas_id() {
  _has_bits_[0] |= 0x00000002u;
}
void d2u_player_login_response::clear_has_gas_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void d2u_player_login_response::clear_gas_id() {
  gas_id_ = 0u;
  clear_has_gas_id();
}
::google::protobuf::uint32 d2u_player_login_response::gas_id() const {
  // @@protoc_insertion_point(field_get:d2u_player_login_response.gas_id)
  return gas_id_;
}
void d2u_player_login_response::set_gas_id(::google::protobuf::uint32 value) {
  set_has_gas_id();
  gas_id_ = value;
  // @@protoc_insertion_point(field_set:d2u_player_login_response.gas_id)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
