// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2u_player_heartbeat_response.proto

#ifndef PROTOBUF_s2u_5fplayer_5fheartbeat_5fresponse_2eproto__INCLUDED
#define PROTOBUF_s2u_5fplayer_5fheartbeat_5fresponse_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class s2u_player_heartbeat_response;
class s2u_player_heartbeat_responseDefaultTypeInternal;
extern s2u_player_heartbeat_responseDefaultTypeInternal _s2u_player_heartbeat_response_default_instance_;

namespace protobuf_s2u_5fplayer_5fheartbeat_5fresponse_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_s2u_5fplayer_5fheartbeat_5fresponse_2eproto

// ===================================================================

class s2u_player_heartbeat_response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s2u_player_heartbeat_response) */ {
 public:
  s2u_player_heartbeat_response();
  virtual ~s2u_player_heartbeat_response();

  s2u_player_heartbeat_response(const s2u_player_heartbeat_response& from);

  inline s2u_player_heartbeat_response& operator=(const s2u_player_heartbeat_response& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const s2u_player_heartbeat_response& default_instance();

  static inline const s2u_player_heartbeat_response* internal_default_instance() {
    return reinterpret_cast<const s2u_player_heartbeat_response*>(
               &_s2u_player_heartbeat_response_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(s2u_player_heartbeat_response* other);

  // implements Message ----------------------------------------------

  inline s2u_player_heartbeat_response* New() const PROTOBUF_FINAL { return New(NULL); }

  s2u_player_heartbeat_response* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const s2u_player_heartbeat_response& from);
  void MergeFrom(const s2u_player_heartbeat_response& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(s2u_player_heartbeat_response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 context = 1;
  bool has_context() const;
  void clear_context();
  static const int kContextFieldNumber = 1;
  ::google::protobuf::uint64 context() const;
  void set_context(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:s2u_player_heartbeat_response)
 private:
  void set_has_context();
  void clear_has_context();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 context_;
  friend struct protobuf_s2u_5fplayer_5fheartbeat_5fresponse_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// s2u_player_heartbeat_response

// required uint64 context = 1;
inline bool s2u_player_heartbeat_response::has_context() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void s2u_player_heartbeat_response::set_has_context() {
  _has_bits_[0] |= 0x00000001u;
}
inline void s2u_player_heartbeat_response::clear_has_context() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void s2u_player_heartbeat_response::clear_context() {
  context_ = GOOGLE_ULONGLONG(0);
  clear_has_context();
}
inline ::google::protobuf::uint64 s2u_player_heartbeat_response::context() const {
  // @@protoc_insertion_point(field_get:s2u_player_heartbeat_response.context)
  return context_;
}
inline void s2u_player_heartbeat_response::set_context(::google::protobuf::uint64 value) {
  set_has_context();
  context_ = value;
  // @@protoc_insertion_point(field_set:s2u_player_heartbeat_response.context)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_s2u_5fplayer_5fheartbeat_5fresponse_2eproto__INCLUDED
