.PHONY: all
all:
	make -C libBaseCommon;
	make -C libBaseNetwork;
	make -C libBaseDatabase;
	make -C libBaseLua;
	make -C libCoreCommon;

.PHONY: clean
clean:
	make -C libBaseCommon clean;
	make -C libBaseNetwork clean;
	make -C libBaseDatabase clean;
	make -C libBaseLua clean;
	make -C libCoreCommon clean;